#!/usr/bin/env bash

cd `brew --prefix`
rm -rf Cellar
bin/brew prune
rm -r Library/Homebrew Library/Aliases Library/Formula Library/Contributions 
test -d Library/LinkedKegs && rm -r Library/LinkedKegs
rmdir -p bin Library share/man/man1 2> /dev/null
rm -rf .git
rm -rf ~/Library/Caches/Homebrew
rm -rf ~/Library/Logs/Homebrew
rm -rf /Library/Caches/Homebrew
rm -rf /usr/local/.git
rm -rf ~/.aliases
rm -rf ~/.exports
rm -rf ~/.gemrc
rm -rf ~/.gitconfig
rm -rf ~/.irbrc
rm -rf ~/.vimrc
rm -rf ~/.profile
rm -rf ~/.pow
rvm implode
yes
curl get.pow.cx/uninstall.sh | sh
touch ~/.bash_profile
source ~/.bash_profile